# Generated by Django 5.0 on 2024-02-26 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Job Category',
            },
        ),
        migrations.CreateModel(
            name='jobCircularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('last_date', models.DateTimeField()),
                ('vacancy', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('job_category', models.ManyToManyField(to='jobs.jobcategorymodel')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Circular',
            },
        ),
        migrations.CreateModel(
            name='jobApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='jobs/resumes/')),
                ('skills', models.CharField(max_length=300)),
                ('coverletter', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcircularmodel')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
