# Generated by Django 5.0 on 2024-02-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobapplicationmodel_applied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='job_circular',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcircularmodel'),
        ),
    ]
