# Generated by Django 5.0 on 2024-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobapplicationmodel_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategorymodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobcategorymodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
