# Generated by Django 5.0 on 2024-02-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobcategorymodel_category_and_more'),
    ]

    operations = [
    ]
