# Generated by Django 5.0 on 2024-02-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobapplicationmodel_job_circular'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='cover_letter',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='resume',
            field=models.FileField(default=None, upload_to='jobs/resume/'),
        ),
    ]
